apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-exec-role-binding
roleRef:
  kind: ClusterRole
  name: pod-exec-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: minikube
  apiGroup: rbac.authorization.k8s.io



