apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app
  labels:
    app: sample-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-python-app
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
      - name: python-app
        image: ravi/python-sample-app-demo:v1
        volumeMounts:
        - name: db-connection
          mountPath: /opt
        - name: db-secrets
          mountPath: /secrets
          readOnly: true
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
      volumes:
      - name: db-connection
        configMap:
          name: test-cm
      - name: db-secrets
        secret:
          secretName: db-secrets
        

