apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec-role-binding
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-exec-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: test-user
  namespace: default

