apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  # Base64-encoded values of your secrets
  db-user: dXNlcg==  # 'user' encoded in base64
  db-password: cGFzc3dvcmQ=  # 'password' encoded in base64

